services:
  db:
    image: postgres:16
    container_name: helpcenter-db
    restart: unless-stopped
    environment:
      POSTGRES_USER: helpcenter_user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: helpcenter
    volumes:
      - db_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  backend:
    build:
      context: .          # root folder
      dockerfile: Dockerfile
    container_name: helpcenter-backend
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload
    environment:
      DATABASE_URL: postgresql+psycopg2://helpcenter_user:password@db:5432/helpcenter
    volumes:
      - .:/code
    ports:
      - "8000:8000"
    depends_on:
      - db

volumes:
  db_data: