services:
  db:
    image: postgres:16
    restart: unless-stopped
    container_name: helpcenter-db
    env_file: .env.local
    volumes:
      - ${DB_VOLUME:-db_data}:/var/lib/postgresql/data
    ports:
      - "${DB_PORT:-5432}:5432"
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U $${POSTGRES_USER} -d $${POSTGRES_DB}" ]
      interval: 10s
      timeout: 5s
      retries: 5

  backend:
    build:
      context: .
    container_name: helpcenter-backend
    restart: unless-stopped
    environment:
      DOCKER_ENV: "1"
      ENVIRONMENT: ${ENVIRONMENT}
    depends_on:
      db:
        condition: service_healthy
    env_file:
      - .env.local
    volumes:
      - .:/app
    ports:
      - "${APP_PORT:-8000}:8000"
    command: >
      sh -c "
      PYTHONPATH=/app ${APP_COMMAND:-uvicorn app.main:app --host 0.0.0.0 --port ${APP_PORT:-8000} --reload}
      "

volumes:
  db_data: