name: HelpCenter Backend CI/CD (UV)

on:
  push:
    branches: [ main, develop ]
    paths:
      - 'common/**'
      - 'graphql_api/**'
      - 'editor_api/**'
      - 'tests/**'
      - 'scripts/**'
      - 'pyproject.toml'
      - 'uv.lock'
      - '.github/workflows/**'
      - 'cloudbuild/**'
  pull_request:
    branches: [ main ]
    paths:
      - 'common/**'
      - 'graphql_api/**'
      - 'editor_api/**'
      - 'tests/**'
      - 'scripts/**'
      - 'pyproject.toml'
      - 'uv.lock'
      - '.github/workflows/**'
      - 'cloudbuild/**'

env:
  PYTHON_VERSION: '3.11'

permissions:
  contents: read
  security-events: write

jobs:
  # Detect what changed to optimize build
  changes:
    runs-on: ubuntu-latest
    outputs:
      common: ${{ steps.changes.outputs.common }}
      graphql_api: ${{ steps.changes.outputs.graphql_api }}
      editor_api: ${{ steps.changes.outputs.editor_api }}
      tests: ${{ steps.changes.outputs.tests }}
      scripts: ${{ steps.changes.outputs.scripts }}
      workflows: ${{ steps.changes.outputs.workflows }}
      cloudbuild: ${{ steps.changes.outputs.cloudbuild }}
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - id: changes
        uses: dorny/paths-filter@v2
        with:
          filters: |
            common:
              - 'common/**'
            graphql_api:
              - 'graphql_api/**'
            editor_api:
              - 'editor_api/**'
            tests:
              - 'tests/**'
            scripts:
              - 'scripts/**'
            workflows:
              - '.github/workflows/**'
            cloudbuild:
              - 'cloudbuild/**'

      - name: Debug changed outputs
        run: |
          echo "=== Changed Components ==="
          echo "common:       ${{ steps.changes.outputs.common }}"
          echo "graphql_api:  ${{ steps.changes.outputs.graphql_api }}"
          echo "editor_api:   ${{ steps.changes.outputs.editor_api }}"
          echo "tests:        ${{ steps.changes.outputs.tests }}"
          echo "scripts:      ${{ steps.changes.outputs.scripts }}"
          echo "workflows:    ${{ steps.changes.outputs.workflows }}"
          echo "cloudbuild:   ${{ steps.changes.outputs.cloudbuild }}"
          echo "==========================="

  # Lint + Test common components
  test-common:
    runs-on: ubuntu-latest
    needs: changes
    if: |
      needs.changes.outputs.common == 'true' ||
      needs.changes.outputs.tests == 'true' ||
      needs.changes.outputs.workflows == 'true'

    services:
      postgres:
        image: postgres:16
        env:
          POSTGRES_USER: test
          POSTGRES_PASSWORD: test
          POSTGRES_DB: test_db
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        ports: [ "5432:5432" ]

      redis:
        image: redis:7-alpine
        options: >-
          --health-cmd "redis-cli ping"
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        ports: [ "6379:6379" ]

    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/setup-uv
      - uses: actions/cache@v4
        with:
          path: |
            .venv
            ~/.cache/uv
          key: uv-${{ runner.os }}-${{ env.PYTHON_VERSION }}-${{ hashFiles('uv.lock') }}
      - run: |
          uv run flake8 common/ --max-line-length=100 --ignore=E203,W503,F821,E402
          uv run black --check common/ --line-length=100
          uv run isort --check-only common/ --profile black
      - run: |
          uv run pytest tests/unit/ -v --cov=common --cov-report=xml
        env:
          TEST_DATABASE_URL_ASYNC: postgresql+asyncpg://test:test@localhost:5432/test_db
          REDIS_URL: redis://localhost:6379
          ENVIRONMENT: test
          SECRET_KEY: test-secret-key
          DEV_EDITOR_KEY: test-editor-key
          GCS_BUCKET_NAME: test-bucket
          ALLOWED_ORIGINS: http://localhost:3000

  # GraphQL API tests
  test-graphql-api:
    runs-on: ubuntu-latest
    needs: [ changes, test-common ]
    if: always() && (
        needs.changes.outputs.graphql_api == 'true' ||
        needs.changes.outputs.common == 'true' ||
        needs.changes.outputs.tests == 'true' ||
        needs.changes.outputs.workflows == 'true'
      )

    services:
      postgres:
        image: postgres:16
        env:
          POSTGRES_USER: test
          POSTGRES_PASSWORD: test
          POSTGRES_DB: test_db
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        ports: [ "5432:5432" ]

      redis:
        image: redis:7-alpine
        options: >-
          --health-cmd "redis-cli ping"
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        ports: [ "6379:6379" ]

    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/setup-uv
      - uses: actions/cache@v4
        with:
          path: |
            .venv
            ~/.cache/uv
          key: uv-${{ runner.os }}-${{ env.PYTHON_VERSION }}-${{ hashFiles('uv.lock') }}
      - run: |
          uv run flake8 graphql_api/ --max-line-length=100 --ignore=E203,W503,F821,E402
          uv run black --check graphql_api/ --line-length=100
          uv run isort --check-only graphql_api/ --profile black
      - run: |
          uv run pytest tests/integration/graphql_api/ -v --cov=graphql_api --cov-report=xml
        env:
          TEST_DATABASE_URL_ASYNC: postgresql+asyncpg://test:test@localhost:5432/test_db
          REDIS_URL: redis://localhost:6379
          ENVIRONMENT: test
          SECRET_KEY: test-secret-key
          DEV_EDITOR_KEY: test-editor-key
          GCS_BUCKET_NAME: test-bucket
          ALLOWED_ORIGINS: http://localhost:3000

  # Editor API tests
  test-editor-api:
    runs-on: ubuntu-latest
    needs: [ changes, test-common ]
    if: always() && (
        needs.changes.outputs.editor_api == 'true' ||
        needs.changes.outputs.common == 'true' ||
        needs.changes.outputs.tests == 'true' ||
        needs.changes.outputs.workflows == 'true'
      )

    services:
      postgres:
        image: postgres:16
        env:
          POSTGRES_USER: test
          POSTGRES_PASSWORD: test
          POSTGRES_DB: test_db
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        ports: [ "5432:5432" ]

      redis:
        image: redis:7-alpine
        options: >-
          --health-cmd "redis-cli ping"
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        ports: [ "6379:6379" ]

    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/setup-uv
      - uses: actions/cache@v4
        with:
          path: |
            .venv
            ~/.cache/uv
          key: uv-${{ runner.os }}-${{ env.PYTHON_VERSION }}-${{ hashFiles('uv.lock') }}
      - run: |
          uv run flake8 editor_api/ --max-line-length=100 --ignore=E203,W503,F821,E402
          uv run black --check editor_api/ --line-length=100
          uv run isort --check-only editor_api/ --profile black
      - run: |
          uv run pytest tests/integration/editor_api/ -v --cov=editor_api --cov-report=xml
        env:
          TEST_DATABASE_URL_ASYNC: postgresql+asyncpg://test:test@localhost:5432/test_db
          REDIS_URL: redis://localhost:6379
          ENVIRONMENT: test
          SECRET_KEY: test-secret-key
          DEV_EDITOR_KEY: test-editor-key
          GCS_BUCKET_NAME: test-bucket
          ALLOWED_ORIGINS: http://localhost:3000

  # Integration
  test-integration:
    runs-on: ubuntu-latest
    needs: [ changes, test-common, test-graphql-api, test-editor-api ]
    if: always()

    services:
      postgres:
        image: postgres:16
        env:
          POSTGRES_USER: test
          POSTGRES_PASSWORD: test
          POSTGRES_DB: test_db
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        ports: [ "5432:5432" ]

      redis:
        image: redis:7-alpine
        options: >-
          --health-cmd "redis-cli ping"
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        ports: [ "6379:6379" ]

    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/setup-uv
      - uses: actions/cache@v4
        with:
          path: |
            .venv
            ~/.cache/uv
          key: uv-${{ runner.os }}-${{ env.PYTHON_VERSION }}-${{ hashFiles('uv.lock') }}
      - run: uv run python -m alembic upgrade head
        env:
          TEST_DATABASE_URL_ASYNC: postgresql+asyncpg://test:test@localhost:5432/test_db
          ENVIRONMENT: test
      - run: uv run pytest tests/integration/ -v
        env:
          TEST_DATABASE_URL_ASYNC: postgresql+asyncpg://test:test@localhost:5432/test_db
          REDIS_URL: redis://localhost:6379
          ENVIRONMENT: test
          SECRET_KEY: test-secret-key
          DEV_EDITOR_KEY: test-editor-key
          GCS_BUCKET_NAME: test-bucket
          ALLOWED_ORIGINS: http://localhost:3000

  # Security
  security:
    runs-on: ubuntu-latest
    needs: changes
    if: |
      needs.changes.outputs.common == 'true' ||
      needs.changes.outputs.graphql_api == 'true' ||
      needs.changes.outputs.editor_api == 'true' ||
      needs.changes.outputs.workflows == 'true'

    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/setup-uv
      - uses: actions/cache@v4
        with:
          path: |
            .venv
            ~/.cache/uv
          key: uv-${{ runner.os }}-${{ env.PYTHON_VERSION }}-${{ hashFiles('uv.lock') }}
      - run: uv run bandit -r common/ graphql_api/ editor_api/ -f json -o bandit-report.json || true
      - uses: actions/upload-artifact@v4
        if: always()
        with:
          name: security-report
          path: bandit-report.json

  # Deploy GraphQL API
  deploy-graphql:
    runs-on: ubuntu-latest
    needs: [ changes, test-common, test-graphql-api, test-integration, security ]
    if: |
      github.event_name == 'push' &&
      (
        needs.changes.outputs.graphql_api == 'true' ||
        needs.changes.outputs.common == 'true' ||
        needs.changes.outputs.cloudbuild == 'true' ||
        needs.changes.outputs.workflows == 'true'
      )
    steps:
      - uses: actions/checkout@v4
      - name: Authenticate to Google Cloud
        uses: google-github-actions/auth@v2
        with:
          credentials_json: ${{ secrets.HELPCENTER_CICD }}
          create_credentials_file: true
          export_environment_variables: true
      - uses: google-github-actions/setup-gcloud@v2
      - id: env
        run: |
          if [[ "${{ github.ref }}" == "refs/heads/main" ]]; then
            echo "environment=production" >> $GITHUB_OUTPUT
          else
            echo "environment=staging" >> $GITHUB_OUTPUT
          fi
      - run: |
          gcloud builds submit \
            --config cloudbuild/cloudbuild-graphql.yaml \
            --substitutions=_ENVIRONMENT=${{ steps.env.outputs.environment }},_GITHUB_SHA=${{ github.sha }} .

  # Deploy Editor API
  deploy-editor:
    runs-on: ubuntu-latest
    needs: [ changes, test-common, test-editor-api, test-integration, security ]
    if: |
      github.event_name == 'push' &&
      (
        needs.changes.outputs.editor_api == 'true' ||
        needs.changes.outputs.common == 'true' ||
        needs.changes.outputs.cloudbuild == 'true' ||
        needs.changes.outputs.workflows == 'true'
      )
    steps:
      - uses: actions/checkout@v4
      - name: Authenticate to Google Cloud
        uses: google-github-actions/auth@v2
        with:
          credentials_json: ${{ secrets.HELPCENTER_CICD }}
          create_credentials_file: true
          export_environment_variables: true
      - uses: google-github-actions/setup-gcloud@v2
      - id: env
        run: |
          if [[ "${{ github.ref }}" == "refs/heads/main" ]]; then
            echo "environment=production" >> $GITHUB_OUTPUT
          else
            echo "environment=staging" >> $GITHUB_OUTPUT
          fi
      - run: |
          gcloud builds submit \
            --config cloudbuild/cloudbuild-editor.yaml \
            --substitutions=_ENVIRONMENT=${{ steps.env.outputs.environment }},_GITHUB_SHA=${{ github.sha }} .
