name: Deploy to Cloud Run

on:
  workflow_call:
    inputs:
      service:
        required: true
        type: string

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: prod
    steps:
      - uses: actions/checkout@v4

      - name: Debug – Check HELPCENTER_CICD secret
        run: |
          if [ -z "${{ secrets.HELPCENTER_CICD }}" ]; then
            echo "ERROR: HELPCENTER_CICD secret missing"
            exit 1
          fi

      - name: Authenticate to Google Cloud
        uses: google-github-actions/auth@v2
        with:
          credentials_json: ${{ secrets.HELPCENTER_CICD }}
          create_credentials_file: true
          export_environment_variables: true

      - uses: google-github-actions/setup-gcloud@v2

      - id: env
        run: |
          if [[ "${{ github.ref }}" == "refs/heads/main" ]]; then
            echo "environment=prod" >> $GITHUB_OUTPUT
          else
            echo "environment=staging" >> $GITHUB_OUTPUT
          fi

      - name: Deploy to Cloud Run
        env:
          GOOGLE_CLOUD_PROJECT: ${{ secrets.GOOGLE_CLOUD_PROJECT }}
          GOOGLE_CLOUD_REGION: ${{ secrets.GOOGLE_CLOUD_REGION }}
          NEON_DB_CONNECTION_STRING: ${{ secrets.NEON_DB_CONNECTION_STRING }}
          REDIS_URL: ${{ secrets.REDIS_URL }}
          SECRET_KEY: ${{ secrets.SECRET_KEY }}
          DEV_EDITOR_KEY: ${{ secrets.DEV_EDITOR_KEY }}
          GCS_BUCKET_NAME: ${{ secrets.GCS_BUCKET_NAME }}
          HELPCENTER_GCS: ${{ secrets.HELPCENTER_GCS }}
          ALLOWED_ORIGINS: ${{ secrets.ALLOWED_ORIGINS }}
        run: |
          echo "Starting Cloud Run deployment for: ${{ inputs.service }}"
          case "${{ inputs.service }}" in
            graphql_api)
              ./scripts/deploy-cloud-run.sh ${{ steps.env.outputs.environment }} ${{ github.sha }}
              ;;
            editor_api)
              ./scripts/deploy-editor.sh ${{ steps.env.outputs.environment }} ${{ github.sha }}
              ;;
            *)
              echo "Unknown service: ${{ inputs.service }}"
              exit 1
              ;;
          esac

      - name: Output deployed URL
        run: |
          SERVICE="helpcenter-${{ inputs.service }}-${{ steps.env.outputs.environment }}"
          URL=$(gcloud run services describe "$SERVICE" \
            --region="${{ secrets.GOOGLE_CLOUD_REGION }}" \
            --format="value(status.url)" || true)
          echo "Deployed URL: ${URL:-<not found>}"
